# Generated by Django 4.1.4 on 2022-12-14 11:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('operator', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('message_text', models.CharField(max_length=500)),
                ('client_filter', models.CharField(max_length=50)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('status', models.IntegerField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.client')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sender.messagequeue')),
            ],
        ),
    ]
