version: '3.8'

services:
  web:
    build: ./
    command: >
      sh -c "python manage.py flush --no-input
             python manage.py makemigrations
             python manage.py migrate
             python manage.py createsuperuser --username djangosender --email root@root.ru --no-input
             python manage.py collectstatic --no-input --clear
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/MessageSender
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  redis:
    image: redis:alpine
  celery:
    restart: always
    build: ./
    command: python -m celery -A MessageSender.celery worker -l info
    volumes:
      - ./:/MessageSender
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: